{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   },
   {
    "name": "datastore",
    "query": "label_values(vmware_datastore_accessible,ds_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ESXi host uptime $esxhost",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "repeat": "esxhost",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} / 32"
      }
     ]
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Host CPU usage ($esxhost)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "repeat": "esxhost",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Host Memory usage ($esxhost)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "repeat": "esxhost",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "DS $datastore vm count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "repeat": "datastore",
     "targets": [
      {
       "expr": "vmware_datastore_vms{ds_name=\"$datastore\"}"
      }
     ]
    },
    {
     "title": "DS $datastore usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
     "repeat": "datastore",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "((vmware_datastore_capacity_size{ds_name=\"$datastore\"}) - (vmware_datastore_freespace_size{ds_name=\"$datastore\"})) * 100 / (vmware_datastore_capacity_size{ds_name=\"$datastore\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "vm CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(vmware_vm_cpu_usagemhz_average{host_name=~\"$esxhost\"}[5m])",
       "legendFormat": "{{ vm_name }}"
      }
     ]
    },
    {
     "title": "vm Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "rate(vmware_vm_mem_usage_average{host_name=~\"$esxhost\"}[5m]) / 4",
       "legendFormat": "{{ vm_name }}"
      }
     ]
    }
   ]
  }
 ]
}