{
 "title": "Jenkins: Performance and Health Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(default_jenkins_up, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "vm_uptime_milliseconds{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "vm_cpu_load{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "vm_memory_total_used{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(vm_memory_total_max{job=\"$job\"} - vm_memory_total_used{job=\"$job\"}) / vm_memory_total_max{job=\"$job\"} * 100.0"
      }
     ]
    }
   ]
  },
  { "title": "Jenkins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_offline_value{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_health_check_score{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_plugins_failed{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_queue_size_value{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration{job=\"$job\"})/sum(jenkins_job_building_duration_count{job=\"$job\"}))",
     "legendFormat": "executors"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_free_value{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count{job=\"$job\"}[$__range])"
    }
   ]
  },
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count{job=\"$job\"}[$__range])"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_builds_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_success_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_failure_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{job=\"$job\"}",
     "legendFormat": "quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds{job=\"$job\"}",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  }
 ]
}